name: Android CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17

      - name: Access KAKAO_APP_KEY
        run: echo KAKAO_APP_KEY=\"$API_KEY\" >> local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.KAKAO_APP_KEY }}

      - name: Access KAKAO_REST_API_KEY
        run: echo KAKAO_REST_API_KEY=\"$API_KEY\" >> local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}

      - name: Access AMPLITUDE_API_KEY
        run: echo AMPLITUDE_API_KEY=\"$API_KEY\" >> local.properties
        shell: bash
        env:
          API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Android Test Report Action
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: Build assemble Debug APK
        run: ./gradlew assembleDebug